import * as path from 'path';
import * as vscode from 'vscode';
import { getManuscript } from './sceneList';
import type { ManuscriptData, SceneMetadataEntry, SceneStatus, CharacterEntry, LocationEntry } from './projectData';

const AI_CONTEXT_DIR = '.noveltools';

function prettySceneName(scenePath: string): string {
  return path.basename(scenePath, '.md').replace(/[-_]/g, ' ');
}

function statusLabel(status: SceneStatus | undefined): string {
  if (!status) return 'unset';
  return status;
}

function buildCharacterRegistry(characters: CharacterEntry[] | undefined): string {
  if (!characters?.length) return '';
  const lines = ['## Characters', ''];
  for (const c of characters) {
    lines.push(`- **${c.name}**${c.description ? `: ${c.description}` : ''}`);
  }
  lines.push('');
  return lines.join('\n');
}

function buildLocationRegistry(locations: LocationEntry[] | undefined): string {
  if (!locations?.length) return '';
  const lines = ['## Locations', ''];
  for (const l of locations) {
    lines.push(`- **${l.name}**${l.description ? `: ${l.description}` : ''}`);
  }
  lines.push('');
  return lines.join('\n');
}

function buildSceneTable(data: ManuscriptData): string {
  const lines = ['## Scene Index', '', '| # | Chapter | Scene | Status | POV | Setting | Timeline | Synopsis |', '|---|---------|-------|--------|-----|---------|----------|----------|'];
  let sceneNum = 0;
  for (let ci = 0; ci < data.chapters.length; ci++) {
    const ch = data.chapters[ci];
    const chTitle = ch.title ?? `Chapter ${ci + 1}`;
    for (let si = 0; si < ch.scenePaths.length; si++) {
      sceneNum++;
      const sp = ch.scenePaths[si];
      const meta = data.sceneMetadata?.[sp] ?? {};
      const status = data.sceneStatus?.[sp];
      lines.push(
        `| ${sceneNum} | ${chTitle} | ${prettySceneName(sp)} | ${statusLabel(status)} | ${meta.pov ?? ''} | ${meta.setting ?? ''} | ${meta.timeline ?? ''} | ${meta.synopsis ?? ''} |`
      );
    }
  }
  lines.push('');
  return lines.join('\n');
}

async function readSceneContent(uri: vscode.Uri): Promise<string> {
  try {
    const doc = await vscode.workspace.openTextDocument(uri);
    return doc.getText().trimEnd();
  } catch {
    return '(file not found)';
  }
}

async function buildFullContext(data: ManuscriptData, includeContent: boolean): Promise<string> {
  const parts: string[] = [];
  const title = data.title?.trim() || 'Untitled Manuscript';
  parts.push(`# ${title} — AI Context Export`, '');
  parts.push(`> Generated by NovelTools on ${new Date().toISOString().slice(0, 10)}`, '');

  const sceneCount = data.flatUris.length;
  const chapterCount = data.chapters.length;
  parts.push(`**${chapterCount} chapters** · **${sceneCount} scenes**`, '');

  parts.push(buildCharacterRegistry(data.characters));
  parts.push(buildLocationRegistry(data.locations));
  parts.push(buildSceneTable(data));

  if (includeContent) {
    parts.push('---', '', '## Full Text', '');
    for (let ci = 0; ci < data.chapters.length; ci++) {
      const ch = data.chapters[ci];
      const chTitle = ch.title ?? `Chapter ${ci + 1}`;
      parts.push(`### ${chTitle}`, '');
      for (let si = 0; si < ch.sceneUris.length; si++) {
        const sp = ch.scenePaths[si];
        const meta = data.sceneMetadata?.[sp] ?? {};
        const status = data.sceneStatus?.[sp];
        parts.push(`#### ${prettySceneName(sp)}`);
        const metaLine = [
          status ? `Status: ${status}` : null,
          meta.pov ? `POV: ${meta.pov}` : null,
          meta.setting ? `Setting: ${meta.setting}` : null,
        ].filter(Boolean).join(' · ');
        if (metaLine) parts.push(`*${metaLine}*`);
        parts.push('');
        const content = await readSceneContent(ch.sceneUris[si]);
        parts.push(content, '');
      }
    }
  }

  return parts.join('\n').trimEnd() + '\n';
}

async function buildContinuityContext(data: ManuscriptData): Promise<string> {
  const parts: string[] = [];
  const title = data.title?.trim() || 'Untitled Manuscript';
  parts.push(`# Continuity Check — ${title}`, '');
  parts.push('> Review the following manuscript for continuity issues. Flag any contradictions in:', '');
  parts.push('> - Character behavior, knowledge, or physical descriptions');
  parts.push('> - Timeline sequence (events happening out of order)');
  parts.push('> - Setting details (places described inconsistently)');
  parts.push('> - Objects, props, or details mentioned then forgotten or contradicted');
  parts.push('> - Character names, spellings, or relationships');
  parts.push('');
  parts.push('> Format each issue as: **Scene** → **Issue** → **Suggestion**');
  parts.push('');

  parts.push(buildCharacterRegistry(data.characters));
  parts.push(buildLocationRegistry(data.locations));
  parts.push(buildSceneTable(data));

  parts.push('---', '', '## Manuscript Text', '');
  for (let ci = 0; ci < data.chapters.length; ci++) {
    const ch = data.chapters[ci];
    const chTitle = ch.title ?? `Chapter ${ci + 1}`;
    parts.push(`### ${chTitle}`, '');
    for (let si = 0; si < ch.sceneUris.length; si++) {
      const sp = ch.scenePaths[si];
      const status = data.sceneStatus?.[sp];
      if (status === 'spiked' || status === 'cut') continue;
      const meta = data.sceneMetadata?.[sp] ?? {};
      parts.push(`#### ${prettySceneName(sp)}`);
      const metaLine = [
        meta.pov ? `POV: ${meta.pov}` : null,
        meta.setting ? `Setting: ${meta.setting}` : null,
        meta.timeline ? `Timeline: ${meta.timeline}` : null,
      ].filter(Boolean).join(' · ');
      if (metaLine) parts.push(`*${metaLine}*`);
      parts.push('');
      const content = await readSceneContent(ch.sceneUris[si]);
      parts.push(content, '');
    }
  }

  return parts.join('\n').trimEnd() + '\n';
}

async function buildSensitivityContext(data: ManuscriptData, scenePaths: string[], guidelines: string): Promise<string> {
  const parts: string[] = [];
  const title = data.title?.trim() || 'Untitled Manuscript';
  parts.push(`# Sensitivity Review — ${title}`, '');
  parts.push('> Review the following scenes for sensitivity concerns. Consider:');
  parts.push('>');
  if (guidelines.trim()) {
    for (const line of guidelines.split('\n')) {
      parts.push(`> ${line.trim()}`);
    }
  } else {
    parts.push('> - Stereotyping or harmful representations of marginalized groups');
    parts.push('> - Cultural appropriation or inaccurate cultural details');
    parts.push('> - Gratuitous violence, especially against vulnerable populations');
    parts.push('> - Language that may be offensive or exclusionary');
    parts.push('> - Power dynamics that reinforce harmful narratives');
  }
  parts.push('');
  parts.push('> For each concern, provide: **Scene** → **Passage** → **Concern** → **Suggested revision**');
  parts.push('');

  parts.push(buildCharacterRegistry(data.characters));
  parts.push('---', '');

  for (const sp of scenePaths) {
    let uri: vscode.Uri | undefined;
    for (const ch of data.chapters) {
      const idx = ch.scenePaths.indexOf(sp);
      if (idx >= 0) { uri = ch.sceneUris[idx]; break; }
    }
    if (!uri) continue;
    const meta = data.sceneMetadata?.[sp] ?? {};
    parts.push(`## ${prettySceneName(sp)}`);
    const metaLine = [
      meta.pov ? `POV: ${meta.pov}` : null,
      meta.setting ? `Setting: ${meta.setting}` : null,
    ].filter(Boolean).join(' · ');
    if (metaLine) parts.push(`*${metaLine}*`);
    parts.push('');
    const content = await readSceneContent(uri);
    parts.push(content, '');
  }

  return parts.join('\n').trimEnd() + '\n';
}

async function buildSceneReviewContext(data: ManuscriptData, scenePath: string, reviewType: string): Promise<string> {
  let uri: vscode.Uri | undefined;
  let chTitle = '';
  for (const ch of data.chapters) {
    const idx = ch.scenePaths.indexOf(scenePath);
    if (idx >= 0) { uri = ch.sceneUris[idx]; chTitle = ch.title ?? 'Untitled Chapter'; break; }
  }
  if (!uri) return '';

  const meta = data.sceneMetadata?.[scenePath] ?? {};
  const status = data.sceneStatus?.[scenePath];
  const content = await readSceneContent(uri);
  const title = data.title?.trim() || 'Untitled Manuscript';

  const parts: string[] = [];
  parts.push(`# ${reviewType} — ${prettySceneName(scenePath)}`, '');
  parts.push(`From *${title}*, chapter "${chTitle}"`, '');

  const prompts: Record<string, string> = {
    'Review': '> Provide a detailed editorial review of this scene. Consider pacing, dialogue, characterization, sensory detail, and emotional impact. Suggest specific improvements.',
    'Expand Outline': '> This scene needs expansion. Based on the synopsis, metadata, and any existing text, generate a detailed scene outline with beats, dialogue hooks, and sensory anchors.',
    'Check Dialogue': '> Review the dialogue in this scene. Check for: natural speech patterns, distinct character voices, dialogue tags, subtext, and pacing. Flag any lines that feel stilted or out of character.',
  };
  parts.push(prompts[reviewType] ?? `> ${reviewType}`, '');

  parts.push('## Scene Metadata', '');
  if (status) parts.push(`- **Status:** ${status}`);
  if (meta.pov) parts.push(`- **POV:** ${meta.pov}`);
  if (meta.setting) parts.push(`- **Setting:** ${meta.setting}`);
  if (meta.timeline) parts.push(`- **Timeline:** ${meta.timeline}`);
  if (meta.synopsis) parts.push(`- **Synopsis:** ${meta.synopsis}`);
  if (meta.tags?.length) parts.push(`- **Tags:** ${meta.tags.join(', ')}`);
  parts.push('');

  parts.push(buildCharacterRegistry(data.characters));

  parts.push('## Scene Text', '');
  parts.push(content, '');

  return parts.join('\n').trimEnd() + '\n';
}

async function writeContextFile(folder: vscode.WorkspaceFolder, filename: string, content: string): Promise<vscode.Uri> {
  const dirUri = vscode.Uri.joinPath(folder.uri, AI_CONTEXT_DIR);
  await vscode.workspace.fs.createDirectory(dirUri);
  const fileUri = vscode.Uri.joinPath(dirUri, filename);
  await vscode.workspace.fs.writeFile(fileUri, Buffer.from(content, 'utf8'));
  return fileUri;
}

export function registerAiWorkflows(context: vscode.ExtensionContext): void {
  // Batch context export
  context.subscriptions.push(
    vscode.commands.registerCommand('noveltools.exportContext', async () => {
      const folder = vscode.workspace.workspaceFolders?.[0];
      if (!folder) return;
      const { data } = await getManuscript();
      if (!data?.flatUris.length) { await vscode.window.showErrorMessage('No manuscript found.'); return; }

      const mode = await vscode.window.showQuickPick([
        { label: 'Metadata only', description: 'Scene table, characters, locations (no scene text)', mode: 'meta' as const },
        { label: 'Full manuscript', description: 'Metadata + all scene text', mode: 'full' as const },
      ], { placeHolder: 'What to include in the AI context export?' });
      if (!mode) return;

      const content = await vscode.window.withProgress(
        { location: vscode.ProgressLocation.Notification, title: 'Exporting context…' },
        () => buildFullContext(data, mode.mode === 'full')
      );

      const fileUri = await writeContextFile(folder, 'noveltools-context.md', content);
      await vscode.window.showTextDocument(fileUri, { preview: false });
      await vscode.window.showInformationMessage(
        `Context exported to ${AI_CONTEXT_DIR}/noveltools-context.md. @-mention this file in chat for AI review.`
      );
    })
  );

  // Continuity check
  context.subscriptions.push(
    vscode.commands.registerCommand('noveltools.continuityCheck', async () => {
      const folder = vscode.workspace.workspaceFolders?.[0];
      if (!folder) return;
      const { data } = await getManuscript();
      if (!data?.flatUris.length) { await vscode.window.showErrorMessage('No manuscript found.'); return; }

      const content = await vscode.window.withProgress(
        { location: vscode.ProgressLocation.Notification, title: 'Building continuity check context…' },
        () => buildContinuityContext(data)
      );

      const fileUri = await writeContextFile(folder, 'noveltools-continuity-check.md', content);
      await vscode.window.showTextDocument(fileUri, { preview: false });
      await vscode.window.showInformationMessage(
        `Continuity check context written to ${AI_CONTEXT_DIR}/noveltools-continuity-check.md. @-mention this file in chat to run the check.`
      );
    })
  );

  // Sensitivity review
  context.subscriptions.push(
    vscode.commands.registerCommand('noveltools.sensitivityReview', async () => {
      const folder = vscode.workspace.workspaceFolders?.[0];
      if (!folder) return;
      const { data } = await getManuscript();
      if (!data?.flatUris.length) { await vscode.window.showErrorMessage('No manuscript found.'); return; }

      const allScenes = data.chapters.flatMap((ch) => ch.scenePaths);
      const items = allScenes.map((sp) => ({
        label: prettySceneName(sp),
        description: data.sceneMetadata?.[sp]?.pov ?? '',
        picked: true,
        scenePath: sp,
      }));
      const picked = await vscode.window.showQuickPick(items, {
        canPickMany: true,
        placeHolder: 'Select scenes to include in sensitivity review',
      });
      if (!picked?.length) return;

      const guidelines = await vscode.window.showInputBox({
        prompt: 'Custom sensitivity guidelines (optional — leave blank for defaults)',
        placeHolder: 'e.g. Focus on representation of disability, check for ableist language',
      }) ?? '';

      const content = await vscode.window.withProgress(
        { location: vscode.ProgressLocation.Notification, title: 'Building sensitivity review context…' },
        () => buildSensitivityContext(data, picked.map((p) => p.scenePath), guidelines)
      );

      const fileUri = await writeContextFile(folder, 'noveltools-sensitivity-review.md', content);
      await vscode.window.showTextDocument(fileUri, { preview: false });
      await vscode.window.showInformationMessage(
        `Sensitivity review context written to ${AI_CONTEXT_DIR}/noveltools-sensitivity-review.md. @-mention this file in chat to run the review.`
      );
    })
  );

  // Scene-level AI actions (right-click on scene)
  const sceneActions = ['Review', 'Expand Outline', 'Check Dialogue'] as const;

  context.subscriptions.push(
    vscode.commands.registerCommand('noveltools.aiReviewScene', (arg?: unknown) => runSceneAiAction(arg, 'Review')),
    vscode.commands.registerCommand('noveltools.aiExpandOutline', (arg?: unknown) => runSceneAiAction(arg, 'Expand Outline')),
    vscode.commands.registerCommand('noveltools.aiCheckDialogue', (arg?: unknown) => runSceneAiAction(arg, 'Check Dialogue'))
  );

  async function runSceneAiAction(arg: unknown, reviewType: string): Promise<void> {
    const folder = vscode.workspace.workspaceFolders?.[0];
    if (!folder) return;
    const { data } = await getManuscript();
    if (!data) return;

    let scenePath: string | undefined;
    if (typeof arg === 'string') {
      scenePath = arg;
    } else if (arg && typeof arg === 'object' && 'data' in arg && 'chapterIndex' in arg && 'sceneIndex' in arg) {
      const node = arg as { data: ManuscriptData; chapterIndex: number; sceneIndex: number };
      scenePath = node.data.chapters[node.chapterIndex]?.scenePaths[node.sceneIndex];
    }

    if (!scenePath) {
      const allScenes = data.chapters.flatMap((ch) => ch.scenePaths);
      const items = allScenes.map((sp) => ({
        label: prettySceneName(sp),
        description: data.sceneMetadata?.[sp]?.synopsis ?? '',
        scenePath: sp,
      }));
      const picked = await vscode.window.showQuickPick(items, { placeHolder: `Select scene for: ${reviewType}` });
      if (!picked) return;
      scenePath = picked.scenePath;
    }

    const content = await buildSceneReviewContext(data, scenePath, reviewType);
    if (!content) { await vscode.window.showErrorMessage('Scene not found in manuscript.'); return; }

    const safeName = prettySceneName(scenePath).replace(/\s+/g, '-').toLowerCase();
    const filename = `noveltools-${reviewType.replace(/\s+/g, '-').toLowerCase()}-${safeName}.md`;
    const fileUri = await writeContextFile(folder, filename, content);
    await vscode.window.showTextDocument(fileUri, { preview: false });
    await vscode.window.showInformationMessage(
      `${reviewType} context for "${prettySceneName(scenePath)}" written to ${AI_CONTEXT_DIR}/${filename}. @-mention this file in chat.`
    );
  }
}
